GLint uniform_ParticleAnimation_scenario_var_data[1] = {NULL};
GLint uniform_Update_scenario_var_data[1] = {NULL};
GLint uniform_Mixing_scenario_var_data[1] = {NULL};
GLint uniform_ParticleRender_scenario_var_data[1] = {NULL};
GLint uniform_Master_scenario_var_data[1] = {NULL};
float *ParticleAnimation_scenario_var_data[1];
float *Update_scenario_var_data[1];
float *Mixing_scenario_var_data[1];
float *ParticleRender_scenario_var_data[1];
float *Master_scenario_var_data[1];
