
 if(pg_current_configuration_rank == 0) {

  glUseProgram(pg_shader_programme[0][_pg_shader_ParticleAnimation]);
  ParticleAnimation_scenario_var_data[0][0] = (GLfloat)partDecay * (1.f + pulse_average * partDecay_pulse);
  ParticleAnimation_scenario_var_data[0][1] = (GLfloat)part_initialization;
  ParticleAnimation_scenario_var_data[0][2] = (GLfloat)part_image_acceleration;
  ParticleAnimation_scenario_var_data[0][3] = (GLfloat)part_path_follow_0;
  ParticleAnimation_scenario_var_data[0][4] = (GLfloat)part_path_follow_1;
  ParticleAnimation_scenario_var_data[0][5] = (GLfloat)part_path_follow_2;
  ParticleAnimation_scenario_var_data[0][6] = (GLfloat)part_path_follow_3;
  ParticleAnimation_scenario_var_data[0][7] = (GLfloat)part_path_follow_4;
  ParticleAnimation_scenario_var_data[0][8] = (GLfloat)part_path_follow_5;
  ParticleAnimation_scenario_var_data[0][9] = (GLfloat)part_path_follow_6;
  ParticleAnimation_scenario_var_data[0][10] = (GLfloat)part_path_follow_7;
  ParticleAnimation_scenario_var_data[0][11] = (GLfloat)part_path_follow_8;
  ParticleAnimation_scenario_var_data[0][12] = (GLfloat)part_path_follow_9;
  ParticleAnimation_scenario_var_data[0][13] = (GLfloat)part_path_follow_10;
  ParticleAnimation_scenario_var_data[0][14] = (GLfloat)part_path_follow_11;
  ParticleAnimation_scenario_var_data[0][15] = (GLfloat)part_path_repulse_0;
  ParticleAnimation_scenario_var_data[0][16] = (GLfloat)part_path_repulse_1;
  ParticleAnimation_scenario_var_data[0][17] = (GLfloat)part_path_repulse_2;
  ParticleAnimation_scenario_var_data[0][18] = (GLfloat)part_path_repulse_3;
  ParticleAnimation_scenario_var_data[0][19] = (GLfloat)part_path_repulse_4;
  ParticleAnimation_scenario_var_data[0][20] = (GLfloat)part_path_repulse_5;
  ParticleAnimation_scenario_var_data[0][21] = (GLfloat)part_path_repulse_6;
  ParticleAnimation_scenario_var_data[0][22] = (GLfloat)part_path_repulse_7;
  ParticleAnimation_scenario_var_data[0][23] = (GLfloat)part_path_repulse_8;
  ParticleAnimation_scenario_var_data[0][24] = (GLfloat)part_path_repulse_9;
  ParticleAnimation_scenario_var_data[0][25] = (GLfloat)part_path_repulse_10;
  ParticleAnimation_scenario_var_data[0][26] = (GLfloat)part_path_repulse_11;
  ParticleAnimation_scenario_var_data[0][27] = (GLfloat)part_size * (1.f + pulse_average * part_size_pulse);
  ParticleAnimation_scenario_var_data[0][28] = (GLfloat)part_acc * (1.f + pulse_average * part_acc_pulse);
  ParticleAnimation_scenario_var_data[0][29] = (GLfloat)part_damp * (1.f + pulse_average * part_damp_pulse);
  ParticleAnimation_scenario_var_data[0][30] = (GLfloat)part_gravity;
  ParticleAnimation_scenario_var_data[0][31] = (GLfloat)noiseParticleScale * (1.f + pulse_average * noiseParticleScale_pulse);
  ParticleAnimation_scenario_var_data[0][32] = (GLfloat)part_field_weight * (1.f + pulse_average * part_field_weight_pulse);
  ParticleAnimation_scenario_var_data[0][33] = (GLfloat)part_damp_targtRad;
  ParticleAnimation_scenario_var_data[0][34] = (GLfloat)part_timeToTargt;
  ParticleAnimation_scenario_var_data[0][35] = (GLfloat)partMove_target;
  ParticleAnimation_scenario_var_data[0][36] = (GLfloat)partMove_rand;
  ParticleAnimation_scenario_var_data[0][37] = (GLfloat)partExit_mode;
  ParticleAnimation_scenario_var_data[0][38] = (GLfloat)partStroke_mode;
  ParticleAnimation_scenario_var_data[0][39] = (GLfloat)partColor_mode;
  ParticleAnimation_scenario_var_data[0][40] = (GLfloat)pixel_acc_shiftX * (1.f + pulse_average * pixel_acc_shiftX_pulse);
  ParticleAnimation_scenario_var_data[0][41] = (GLfloat)pixel_acc_shiftY * (1.f + pulse_average * pixel_acc_shiftY_pulse);
  ParticleAnimation_scenario_var_data[0][42] = (GLfloat)repop_part * (1.f + pulse_average * repop_part_pulse);
  ParticleAnimation_scenario_var_data[0][43] = (GLfloat)repop_path * (1.f + pulse_average * repop_path_pulse);
  ParticleAnimation_scenario_var_data[0][44] = (GLfloat)Part_repop_density;
  ParticleAnimation_scenario_var_data[0][45] = (GLfloat)Part_repop_color_mode;
  ParticleAnimation_scenario_var_data[0][46] = (GLfloat)freeze;
  glUniform1fv(uniform_ParticleAnimation_scenario_var_data[0], 47, ParticleAnimation_scenario_var_data[0]);

  glUseProgram(pg_shader_programme[0][_pg_shader_Update]);
  Update_scenario_var_data[0][0] = (GLfloat)camera_BG_subtr;
  Update_scenario_var_data[0][1] = (GLfloat)CAdecay + pulse_average * CAdecay_pulse;
  Update_scenario_var_data[0][2] = (GLfloat)trkDecay_0 * (1.f + pulse_average * trkDecay_0_pulse);
  Update_scenario_var_data[0][3] = (GLfloat)trkDecay_1 * (1.f + pulse_average * trkDecay_1_pulse);
  Update_scenario_var_data[0][4] = (GLfloat)trkDecay_2 * (1.f + pulse_average * trkDecay_2_pulse);
  Update_scenario_var_data[0][5] = (GLfloat)trkDecay_3 * (1.f + pulse_average * trkDecay_3_pulse);
  Update_scenario_var_data[0][6] = (GLfloat)currentDrawingTrack;
  Update_scenario_var_data[0][7] = (GLfloat)currentVideoTrack;
  Update_scenario_var_data[0][8] = (GLfloat)currentPhotoTrack;
  Update_scenario_var_data[0][9] = (GLfloat)path_replay_trackNo_1;
  Update_scenario_var_data[0][10] = (GLfloat)path_replay_trackNo_2;
  Update_scenario_var_data[0][11] = (GLfloat)path_replay_trackNo_3;
  Update_scenario_var_data[0][12] = (GLfloat)path_replay_trackNo_4;
  Update_scenario_var_data[0][13] = (GLfloat)path_replay_trackNo_5;
  Update_scenario_var_data[0][14] = (GLfloat)path_replay_trackNo_6;
  Update_scenario_var_data[0][15] = (GLfloat)path_replay_trackNo_7;
  Update_scenario_var_data[0][16] = (GLfloat)path_replay_trackNo_8;
  Update_scenario_var_data[0][17] = (GLfloat)path_replay_trackNo_9;
  Update_scenario_var_data[0][18] = (GLfloat)path_replay_trackNo_10;
  Update_scenario_var_data[0][19] = (GLfloat)path_replay_trackNo_11;
  Update_scenario_var_data[0][20] = (GLfloat)noiseUpdateScale * (1.f + pulse_average * noiseUpdateScale_pulse);
  Update_scenario_var_data[0][21] = (GLfloat)pixel_acc * (1.f + pulse_average * pixel_acc_pulse);
  Update_scenario_var_data[0][22] = (GLfloat)pixel_acc_shiftX * (1.f + pulse_average * pixel_acc_shiftX_pulse);
  Update_scenario_var_data[0][23] = (GLfloat)pixel_acc_shiftY * (1.f + pulse_average * pixel_acc_shiftY_pulse);
  Update_scenario_var_data[0][24] = (GLfloat)pixel_radius * (1.f + pulse_average * pixel_radius_pulse);
  Update_scenario_var_data[0][25] = (GLfloat)pixel_mode;
  Update_scenario_var_data[0][26] = (GLfloat)repop_CA * (1.f + pulse_average * repop_CA_pulse);
  Update_scenario_var_data[0][27] = (GLfloat)repop_BG * (1.f + pulse_average * repop_BG_pulse);
  Update_scenario_var_data[0][28] = (GLfloat)BG_CA_repop_density;
  Update_scenario_var_data[0][29] = (GLfloat)BG_CA_repop_color_mode;
  Update_scenario_var_data[0][30] = (GLfloat)cameraGamma;
  Update_scenario_var_data[0][31] = (GLfloat)camera_gamma;
  Update_scenario_var_data[0][32] = (GLfloat)activeClipArts;
  Update_scenario_var_data[0][33] = (GLfloat)cameraThreshold * (1.f + pulse_average * cameraThreshold_pulse);
  Update_scenario_var_data[0][34] = (GLfloat)cameraWeight * (1.f + pulse_average * cameraWeight_pulse);
  Update_scenario_var_data[0][35] = (GLfloat)cameraSobel * (1.f + pulse_average * cameraSobel_pulse);
  Update_scenario_var_data[0][36] = (GLfloat)movieWeight * (1.f + pulse_average * movieWeight_pulse);
  Update_scenario_var_data[0][37] = (GLfloat)movieSobel * (1.f + pulse_average * movieSobel_pulse);
  Update_scenario_var_data[0][38] = (GLfloat)invertMovie;
  Update_scenario_var_data[0][39] = (GLfloat)invertCamera;
  Update_scenario_var_data[0][40] = (GLfloat)invertPhoto;
  Update_scenario_var_data[0][41] = (GLfloat)video_satur * (1.f + pulse_average * video_satur_pulse);
  Update_scenario_var_data[0][42] = (GLfloat)video_satur_pulse;
  Update_scenario_var_data[0][43] = (GLfloat)video_value * (1.f + pulse_average * video_value_pulse);
  Update_scenario_var_data[0][44] = (GLfloat)movie_gamma * (1.f + pulse_average * movie_gamma_pulse);
  Update_scenario_var_data[0][45] = (GLfloat)movie_threshold * (1.f + pulse_average * movie_threshold_pulse);
  Update_scenario_var_data[0][46] = (GLfloat)video_gamma * (1.f + pulse_average * video_gamma_pulse);
  Update_scenario_var_data[0][47] = (GLfloat)video_threshold * (1.f + pulse_average * video_threshold_pulse);
  Update_scenario_var_data[0][48] = (GLfloat)video_contrast * (1.f + pulse_average * video_contrast_pulse);
  Update_scenario_var_data[0][49] = (GLfloat)photoWeight * (1.f + pulse_average * photoWeight_pulse);
  Update_scenario_var_data[0][50] = (GLfloat)photo_satur * (1.f + pulse_average * photo_satur_pulse);
  Update_scenario_var_data[0][51] = (GLfloat)photo_satur_pulse;
  Update_scenario_var_data[0][52] = (GLfloat)photo_value * (1.f + pulse_average * photo_value_pulse);
  Update_scenario_var_data[0][53] = (GLfloat)photo_value_pulse;
  Update_scenario_var_data[0][54] = (GLfloat)photo_gamma * (1.f + pulse_average * photo_gamma_pulse);
  Update_scenario_var_data[0][55] = (GLfloat)photo_gamma_pulse;
  Update_scenario_var_data[0][56] = (GLfloat)photo_threshold * (1.f + pulse_average * photo_threshold_pulse);
  Update_scenario_var_data[0][57] = (GLfloat)photoSobel * (1.f + pulse_average * photoSobel_pulse);
  Update_scenario_var_data[0][58] = (GLfloat)photo_scaleX;
  Update_scenario_var_data[0][59] = (GLfloat)photo_scaleY;
  Update_scenario_var_data[0][60] = (GLfloat)photo_rot;
  Update_scenario_var_data[0][61] = (GLfloat)photo_transl_x;
  Update_scenario_var_data[0][62] = (GLfloat)photo_transl_y;
  Update_scenario_var_data[0][63] = (GLfloat)mask_scale;
  Update_scenario_var_data[0][64] = (GLfloat)photo_contrast;
  Update_scenario_var_data[0][65] = (GLfloat)mask_contrast;
  Update_scenario_var_data[0][66] = (GLfloat)CAParams1 * (1.f + pulse_average * CAParams1_pulse);
  Update_scenario_var_data[0][67] = (GLfloat)CAParams2 * (1.f + pulse_average * CAParams2_pulse);
  Update_scenario_var_data[0][68] = (GLfloat)CAParams3 * (1.f + pulse_average * CAParams3_pulse);
  Update_scenario_var_data[0][69] = (GLfloat)CAParams4 * (1.f + pulse_average * CAParams4_pulse);
  Update_scenario_var_data[0][70] = (GLfloat)CAParams5 * (1.f + pulse_average * CAParams5_pulse);
  Update_scenario_var_data[0][71] = (GLfloat)CAParams6 * (1.f + pulse_average * CAParams6_pulse);
  Update_scenario_var_data[0][72] = (GLfloat)CAParams7 * (1.f + pulse_average * CAParams7_pulse);
  Update_scenario_var_data[0][73] = (GLfloat)CAParams8 * (1.f + pulse_average * CAParams8_pulse);
  Update_scenario_var_data[0][74] = (GLfloat)cameraCumul;
  Update_scenario_var_data[0][75] = (GLfloat)CAstep;
  Update_scenario_var_data[0][76] = (GLfloat)Pixelstep;
  Update_scenario_var_data[0][77] = (GLfloat)CAcolorSpread;
  Update_scenario_var_data[0][78] = (GLfloat)freeze;
  Update_scenario_var_data[0][79] = (GLfloat)video_white * (1.f + pulse_average * video_white_pulse);
  Update_scenario_var_data[0][80] = (GLfloat)video_hue * (1.f + pulse_average * video_hue_pulse);
  Update_scenario_var_data[0][81] = (GLfloat)photo_hue * (1.f + pulse_average * photo_hue_pulse);
  glUniform1fv(uniform_Update_scenario_var_data[0], 82, Update_scenario_var_data[0]);

  glUseProgram(pg_shader_programme[0][_pg_shader_Mixing]);
  Mixing_scenario_var_data[0][0] = (GLfloat)CAMixingWeight + pulse_average * CAMixingWeight_pulse;
  Mixing_scenario_var_data[0][1] = (GLfloat)PartMixingWeight + pulse_average * PartMixingWeight_pulse;
  Mixing_scenario_var_data[0][2] = (GLfloat)trackMixingWeight_0 + pulse_average * trackMixingWeight_0_pulse;
  Mixing_scenario_var_data[0][3] = (GLfloat)trackMixingWeight_1 + pulse_average * trackMixingWeight_1_pulse;
  Mixing_scenario_var_data[0][4] = (GLfloat)trackMixingWeight_2 + pulse_average * trackMixingWeight_2_pulse;
  Mixing_scenario_var_data[0][5] = (GLfloat)trackMixingWeight_3 + pulse_average * trackMixingWeight_3_pulse;
  Mixing_scenario_var_data[0][6] = (GLfloat)echo * (1.f + pulse_average * echo_pulse);
  Mixing_scenario_var_data[0][7] = (GLfloat)echoNeg * (1.f + pulse_average * echoNeg_pulse);
  glUniform1fv(uniform_Mixing_scenario_var_data[0], 8, Mixing_scenario_var_data[0]);

  glUseProgram(pg_shader_programme[0][_pg_shader_ParticleRender]);

  glUseProgram(pg_shader_programme[0][_pg_shader_Master]);
  Master_scenario_var_data[0][0] = (GLfloat)mute_second_screen;
  Master_scenario_var_data[0][1] = (GLfloat)invertAllLayers;
  Master_scenario_var_data[0][2] = (GLfloat)cursorSize;
  Master_scenario_var_data[0][3] = (GLfloat)master;
  Master_scenario_var_data[0][4] = (GLfloat)CAMasterWeight + pulse_average * CAMasterWeight_pulse;
  Master_scenario_var_data[0][5] = (GLfloat)PartMasterWeight + pulse_average * PartMasterWeight_pulse;
  Master_scenario_var_data[0][6] = (GLfloat)trackMasterWeight_0 + pulse_average * trackMasterWeight_0_pulse;
  Master_scenario_var_data[0][7] = (GLfloat)trackMasterWeight_1 + pulse_average * trackMasterWeight_1_pulse;
  Master_scenario_var_data[0][8] = (GLfloat)trackMasterWeight_2 + pulse_average * trackMasterWeight_2_pulse;
  Master_scenario_var_data[0][9] = (GLfloat)trackMasterWeight_3 + pulse_average * trackMasterWeight_3_pulse;
  Master_scenario_var_data[0][10] = (GLfloat)SecondMasterMixingWeight;
  Master_scenario_var_data[0][11] = (GLfloat)currentMaskTrack;
  Master_scenario_var_data[0][12] = (GLfloat)master_scale * (1.f + pulse_average * master_scale_pulse);
  Master_scenario_var_data[0][13] = (GLfloat)master_scale_pulse;
  Master_scenario_var_data[0][14] = (GLfloat)master_scale_ratio;
  Master_scenario_var_data[0][15] = (GLfloat)master_offsetX;
  Master_scenario_var_data[0][16] = (GLfloat)master_offsetY;
  Master_scenario_var_data[0][17] = (GLfloat)master_mask_opacity_1;
  Master_scenario_var_data[0][18] = (GLfloat)master_mask_opacity_2;
  Master_scenario_var_data[0][19] = (GLfloat)master_mask_opacity_3;
  Master_scenario_var_data[0][20] = (GLfloat)master_mask_opacity_4;
  Master_scenario_var_data[0][21] = (GLfloat)master_mask_opacity_5;
  Master_scenario_var_data[0][22] = (GLfloat)master_mask_opacity_6;
  Master_scenario_var_data[0][23] = (GLfloat)master_crop_x;
  Master_scenario_var_data[0][24] = (GLfloat)master_crop_y;
  Master_scenario_var_data[0][25] = (GLfloat)master_crop_width;
  Master_scenario_var_data[0][26] = (GLfloat)master_mask;
  Master_scenario_var_data[0][27] = (GLfloat)master_mask_scale;
  Master_scenario_var_data[0][28] = (GLfloat)master_mask_scale_ratio;
  Master_scenario_var_data[0][29] = (GLfloat)master_mask_offsetX;
  Master_scenario_var_data[0][30] = (GLfloat)master_mask_offsetY;
  Master_scenario_var_data[0][31] = (GLfloat)Argenteuil_bugs + pulse_average * Argenteuil_bugs_pulse;
  glUniform1fv(uniform_Master_scenario_var_data[0], 32, Master_scenario_var_data[0]);

 }
