GLint uniform_Update_scenario_var_data;
GLint uniform_Master_scenario_var_data;
GLint uniform_Mixing_scenario_var_data;
GLint uniform_ParticleAnimation_scenario_var_data;
float ParticleAnimation_scenario_var_data[44];
float Update_scenario_var_data[69];
float Mixing_scenario_var_data[8];
float Master_scenario_var_data[25];
