GLint uniform_ParticleAnimation_scenario_var_data[1] = {0};
GLint uniform_Update_scenario_var_data[1] = {0};
GLint uniform_Mixing_scenario_var_data[1] = {0};
GLint uniform_ParticleRender_scenario_var_data[1] = {0};
GLint uniform_Master_scenario_var_data[1] = {0};
float *ParticleAnimation_scenario_var_data;
float *Update_scenario_var_data;
float *Mixing_scenario_var_data;
float *ParticleRender_scenario_var_data;
float *Master_scenario_var_data;
