
 glUseProgram(shader_programme[pg_shader_ParticleAnimation]);
 ParticleAnimation_scenario_var_data[0] = (GLfloat)partDecay * (1.f + pulse_average * partDecay_pulse);
 ParticleAnimation_scenario_var_data[1] = (GLfloat)part_initialization;
 ParticleAnimation_scenario_var_data[2] = (GLfloat)part_path_follow_0;
 ParticleAnimation_scenario_var_data[3] = (GLfloat)part_path_follow_1;
 ParticleAnimation_scenario_var_data[4] = (GLfloat)part_path_follow_2;
 ParticleAnimation_scenario_var_data[5] = (GLfloat)part_path_follow_3;
 ParticleAnimation_scenario_var_data[6] = (GLfloat)part_path_follow_4;
 ParticleAnimation_scenario_var_data[7] = (GLfloat)part_path_follow_5;
 ParticleAnimation_scenario_var_data[8] = (GLfloat)part_path_follow_6;
 ParticleAnimation_scenario_var_data[9] = (GLfloat)part_path_follow_7;
 ParticleAnimation_scenario_var_data[10] = (GLfloat)part_path_repulse_0;
 ParticleAnimation_scenario_var_data[11] = (GLfloat)part_path_repulse_1;
 ParticleAnimation_scenario_var_data[12] = (GLfloat)part_path_repulse_2;
 ParticleAnimation_scenario_var_data[13] = (GLfloat)part_path_repulse_3;
 ParticleAnimation_scenario_var_data[14] = (GLfloat)part_path_repulse_4;
 ParticleAnimation_scenario_var_data[15] = (GLfloat)part_path_repulse_5;
 ParticleAnimation_scenario_var_data[16] = (GLfloat)part_path_repulse_6;
 ParticleAnimation_scenario_var_data[17] = (GLfloat)part_path_repulse_7;
 ParticleAnimation_scenario_var_data[18] = (GLfloat)part_size * (1.f + pulse_average * part_size_pulse);
 ParticleAnimation_scenario_var_data[19] = (GLfloat)part_acc * (1.f + pulse_average * part_acc_pulse);
 ParticleAnimation_scenario_var_data[20] = (GLfloat)part_damp * (1.f + pulse_average * part_damp_pulse);
 ParticleAnimation_scenario_var_data[21] = (GLfloat)noiseScale * (1.f + pulse_average * noiseScale_pulse);
 ParticleAnimation_scenario_var_data[22] = (GLfloat)part_field_weight * (1.f + pulse_average * part_field_weight_pulse);
 ParticleAnimation_scenario_var_data[23] = (GLfloat)part_damp_targtRad;
 ParticleAnimation_scenario_var_data[24] = (GLfloat)part_timeToTargt;
 ParticleAnimation_scenario_var_data[25] = (GLfloat)partMove_target;
 ParticleAnimation_scenario_var_data[26] = (GLfloat)partMove_rand;
 ParticleAnimation_scenario_var_data[27] = (GLfloat)partExit_mode;
 ParticleAnimation_scenario_var_data[28] = (GLfloat)partStroke_mode;
 ParticleAnimation_scenario_var_data[29] = (GLfloat)partColor_mode;
 ParticleAnimation_scenario_var_data[30] = (GLfloat)pixel_acc_shiftX * (1.f + pulse_average * pixel_acc_shiftX_pulse);
 ParticleAnimation_scenario_var_data[31] = (GLfloat)pixel_acc_shiftY * (1.f + pulse_average * pixel_acc_shiftY_pulse);
 ParticleAnimation_scenario_var_data[32] = (GLfloat)repop_part * (1.f + pulse_average * repop_part_pulse);
 ParticleAnimation_scenario_var_data[33] = (GLfloat)repop_path * (1.f + pulse_average * repop_path_pulse);
 ParticleAnimation_scenario_var_data[34] = (GLfloat)freeze;
 glUniform1fv( uniform_ParticleAnimation_scenario_var_data, 35, ParticleAnimation_scenario_var_data);

 glUseProgram(shader_programme[pg_shader_Update]);
 Update_scenario_var_data[0] = (GLfloat)camera_BG_subtr;
 Update_scenario_var_data[1] = (GLfloat)CAdecay * (1.f + pulse_average * CAdecay_pulse);
 Update_scenario_var_data[2] = (GLfloat)trkDecay_0 * (1.f + pulse_average * trkDecay_0_pulse);
 Update_scenario_var_data[3] = (GLfloat)trkDecay_1 * (1.f + pulse_average * trkDecay_1_pulse);
 Update_scenario_var_data[4] = (GLfloat)trkDecay_2 * (1.f + pulse_average * trkDecay_2_pulse);
 Update_scenario_var_data[5] = (GLfloat)trkDecay_3 * (1.f + pulse_average * trkDecay_3_pulse);
 Update_scenario_var_data[6] = (GLfloat)currentDrawingTrack;
 Update_scenario_var_data[7] = (GLfloat)currentVideoTrack;
 Update_scenario_var_data[8] = (GLfloat)currentPhotoTrack;
 Update_scenario_var_data[9] = (GLfloat)path_replay_trackNo_1;
 Update_scenario_var_data[10] = (GLfloat)path_replay_trackNo_2;
 Update_scenario_var_data[11] = (GLfloat)path_replay_trackNo_3;
 Update_scenario_var_data[12] = (GLfloat)path_replay_trackNo_4;
 Update_scenario_var_data[13] = (GLfloat)path_replay_trackNo_5;
 Update_scenario_var_data[14] = (GLfloat)path_replay_trackNo_6;
 Update_scenario_var_data[15] = (GLfloat)path_replay_trackNo_7;
 Update_scenario_var_data[16] = (GLfloat)noiseScale * (1.f + pulse_average * noiseScale_pulse);
 Update_scenario_var_data[17] = (GLfloat)noiseType;
 Update_scenario_var_data[18] = (GLfloat)noiseLineScale;
 Update_scenario_var_data[19] = (GLfloat)noiseAngleScale;
 Update_scenario_var_data[20] = (GLfloat)noiseCenterX;
 Update_scenario_var_data[21] = (GLfloat)noiseCenterY;
 Update_scenario_var_data[22] = (GLfloat)pixel_acc * (1.f + pulse_average * pixel_acc_pulse);
 Update_scenario_var_data[23] = (GLfloat)pixel_acc_shiftX * (1.f + pulse_average * pixel_acc_shiftX_pulse);
 Update_scenario_var_data[24] = (GLfloat)pixel_acc_shiftY * (1.f + pulse_average * pixel_acc_shiftY_pulse);
 Update_scenario_var_data[25] = (GLfloat)pixel_radius * (1.f + pulse_average * pixel_radius_pulse);
 Update_scenario_var_data[26] = (GLfloat)pixel_mode;
 Update_scenario_var_data[27] = (GLfloat)repop_CA * (1.f + pulse_average * repop_CA_pulse);
 Update_scenario_var_data[28] = (GLfloat)repop_BG * (1.f + pulse_average * repop_BG_pulse);
 Update_scenario_var_data[29] = (GLfloat)repop_density;
 Update_scenario_var_data[30] = (GLfloat)cameraGamma;
 Update_scenario_var_data[31] = (GLfloat)activeClipArts;
 Update_scenario_var_data[32] = (GLfloat)cameraThreshold * (1.f + pulse_average * cameraThreshold_pulse);
 Update_scenario_var_data[33] = (GLfloat)cameraWeight * (1.f + pulse_average * cameraWeight_pulse);
 Update_scenario_var_data[34] = (GLfloat)cameraSobel * (1.f + pulse_average * cameraSobel_pulse);
 Update_scenario_var_data[35] = (GLfloat)movieWeight * (1.f + pulse_average * movieWeight_pulse);
 Update_scenario_var_data[36] = (GLfloat)movieSobel * (1.f + pulse_average * movieSobel_pulse);
 Update_scenario_var_data[37] = (GLfloat)invertMovie;
 Update_scenario_var_data[38] = (GLfloat)video_satur * (1.f + pulse_average * video_satur_pulse);
 Update_scenario_var_data[39] = (GLfloat)video_satur_pulse;
 Update_scenario_var_data[40] = (GLfloat)video_value * (1.f + pulse_average * video_value_pulse);
 Update_scenario_var_data[41] = (GLfloat)photoWeight * (1.f + pulse_average * photoWeight_pulse);
 Update_scenario_var_data[42] = (GLfloat)photo_satur * (1.f + pulse_average * photo_satur_pulse);
 Update_scenario_var_data[43] = (GLfloat)photo_satur_pulse;
 Update_scenario_var_data[44] = (GLfloat)photo_value * (1.f + pulse_average * photo_value_pulse);
 Update_scenario_var_data[45] = (GLfloat)photo_value_pulse;
 Update_scenario_var_data[46] = (GLfloat)photo_scale;
 Update_scenario_var_data[47] = (GLfloat)mask_scale;
 Update_scenario_var_data[48] = (GLfloat)photo_contrast;
 Update_scenario_var_data[49] = (GLfloat)mask_contrast;
 Update_scenario_var_data[50] = (GLfloat)CAParams1 * (1.f + pulse_average * CAParams1_pulse);
 Update_scenario_var_data[51] = (GLfloat)CAParams2 * (1.f + pulse_average * CAParams2_pulse);
 Update_scenario_var_data[52] = (GLfloat)CAParams3 * (1.f + pulse_average * CAParams3_pulse);
 Update_scenario_var_data[53] = (GLfloat)CAParams4 * (1.f + pulse_average * CAParams4_pulse);
 Update_scenario_var_data[54] = (GLfloat)CAParams5 * (1.f + pulse_average * CAParams5_pulse);
 Update_scenario_var_data[55] = (GLfloat)CAParams6 * (1.f + pulse_average * CAParams6_pulse);
 Update_scenario_var_data[56] = (GLfloat)CAParams7 * (1.f + pulse_average * CAParams7_pulse);
 Update_scenario_var_data[57] = (GLfloat)CAParams8 * (1.f + pulse_average * CAParams8_pulse);
 Update_scenario_var_data[58] = (GLfloat)cameraCumul;
 Update_scenario_var_data[59] = (GLfloat)CAstep;
 Update_scenario_var_data[60] = (GLfloat)CAcolorSpread;
 Update_scenario_var_data[61] = (GLfloat)freeze;
 glUniform1fv( uniform_Update_scenario_var_data, 62, Update_scenario_var_data);

 glUseProgram(shader_programme[pg_shader_Mixing]);
 Mixing_scenario_var_data[0] = (GLfloat)CAMixingWeight * (1.f + pulse_average * CAMixingWeight_pulse) ;
 Mixing_scenario_var_data[1] = (GLfloat)PartMixingWeight * (1.f + pulse_average * PartMixingWeight_pulse) ;
 Mixing_scenario_var_data[2] = (GLfloat)trackMixingWeight_0 * (1.f + pulse_average * trackMixingWeight_0_pulse) ;
 Mixing_scenario_var_data[3] = (GLfloat)trackMixingWeight_1 * (1.f + pulse_average * trackMixingWeight_1_pulse) ;
 Mixing_scenario_var_data[4] = (GLfloat)trackMixingWeight_2 * (1.f + pulse_average * trackMixingWeight_2_pulse) ;
 Mixing_scenario_var_data[5] = (GLfloat)trackMixingWeight_3 * (1.f + pulse_average * trackMixingWeight_3_pulse) ;
 Mixing_scenario_var_data[6] = (GLfloat)echo * (1.f + pulse_average * echo_pulse) ;
 Mixing_scenario_var_data[7] = (GLfloat)echoNeg * (1.f + pulse_average * echoNeg_pulse) ;
 glUniform1fv( uniform_Mixing_scenario_var_data, 8, Mixing_scenario_var_data);

 glUseProgram(shader_programme[pg_shader_ParticleRender]);

 glUseProgram(shader_programme[pg_shader_Master]);
 Master_scenario_var_data[0] = (GLfloat)mute_second_screen;
 Master_scenario_var_data[1] = (GLfloat)invertAllLayers;
 Master_scenario_var_data[2] = (GLfloat)cursorSize;
 Master_scenario_var_data[3] = (GLfloat)master;
 Master_scenario_var_data[4] = (GLfloat)CAMasterWeight * (1.f + pulse_average * CAMasterWeight_pulse);
 Master_scenario_var_data[5] = (GLfloat)PartMasterWeight * (1.f + pulse_average * PartMasterWeight_pulse);
 Master_scenario_var_data[6] = (GLfloat)trackMasterWeight_0 * (1.f + pulse_average * trackMasterWeight_0_pulse);
 Master_scenario_var_data[7] = (GLfloat)trackMasterWeight_1 * (1.f + pulse_average * trackMasterWeight_1_pulse);
 Master_scenario_var_data[8] = (GLfloat)trackMasterWeight_2 * (1.f + pulse_average * trackMasterWeight_2_pulse);
 Master_scenario_var_data[9] = (GLfloat)trackMasterWeight_3 * (1.f + pulse_average * trackMasterWeight_3_pulse);
 Master_scenario_var_data[10] = (GLfloat)interfaceOnScreen;
 glUniform1fv( uniform_Master_scenario_var_data, 11, Master_scenario_var_data);
