
 glUseProgram(shader_programme[pg_shader_Update]);
 Update_scenario_var_data[0] = (GLfloat)camera_BG_subtr;
 Update_scenario_var_data[1] = (GLfloat)CAdecay * (1.f + pulse_average * CAdecay_pulse);
 Update_scenario_var_data[2] = (GLfloat)trkDecay_0 * (1.f + pulse_average * trkDecay_0_pulse);
 Update_scenario_var_data[3] = (GLfloat)trkDecay_1 * (1.f + pulse_average * trkDecay_1_pulse);
 Update_scenario_var_data[4] = (GLfloat)currentDrawingTrack;
 Update_scenario_var_data[5] = (GLfloat)currentVideoTrack;
 Update_scenario_var_data[6] = (GLfloat)currentPhotoTrack;
 Update_scenario_var_data[7] = (GLfloat)path_replay_trackNo_1;
 Update_scenario_var_data[8] = (GLfloat)path_replay_trackNo_2;
 Update_scenario_var_data[9] = (GLfloat)path_replay_trackNo_3;
 Update_scenario_var_data[10] = (GLfloat)path_replay_trackNo_4;
 Update_scenario_var_data[11] = (GLfloat)path_replay_trackNo_5;
 Update_scenario_var_data[12] = (GLfloat)path_replay_trackNo_6;
 Update_scenario_var_data[13] = (GLfloat)path_replay_trackNo_7;
 Update_scenario_var_data[14] = (GLfloat)noiseScale * (1.f + pulse_average * noiseScale_pulse);
 Update_scenario_var_data[15] = (GLfloat)pixel_acc * (1.f + pulse_average * pixel_acc_pulse);
 Update_scenario_var_data[16] = (GLfloat)pixel_acc_shiftX * (1.f + pulse_average * pixel_acc_shiftX_pulse);
 Update_scenario_var_data[17] = (GLfloat)pixel_acc_shiftY * (1.f + pulse_average * pixel_acc_shiftY_pulse);
 Update_scenario_var_data[18] = (GLfloat)pixel_radius * (1.f + pulse_average * pixel_radius_pulse);
 Update_scenario_var_data[19] = (GLfloat)pixel_mode;
 Update_scenario_var_data[20] = (GLfloat)repop_BG * (1.f + pulse_average * repop_BG_pulse);
 Update_scenario_var_data[21] = (GLfloat)cameraGamma;
 Update_scenario_var_data[22] = (GLfloat)activeClipArts;
 Update_scenario_var_data[23] = (GLfloat)cameraThreshold * (1.f + pulse_average * cameraThreshold_pulse);
 Update_scenario_var_data[24] = (GLfloat)cameraWeight * (1.f + pulse_average * cameraWeight_pulse);
 Update_scenario_var_data[25] = (GLfloat)cameraSobel * (1.f + pulse_average * cameraSobel_pulse);
 Update_scenario_var_data[26] = (GLfloat)movieWeight * (1.f + pulse_average * movieWeight_pulse);
 Update_scenario_var_data[27] = (GLfloat)movieSobel * (1.f + pulse_average * movieSobel_pulse);
 Update_scenario_var_data[28] = (GLfloat)invertMovie;
 Update_scenario_var_data[29] = (GLfloat)video_hue * (1.f + pulse_average * video_hue_pulse);
 Update_scenario_var_data[30] = (GLfloat)video_satur * (1.f + pulse_average * video_satur_pulse);
 Update_scenario_var_data[31] = (GLfloat)video_satur_pulse;
 Update_scenario_var_data[32] = (GLfloat)video_value * (1.f + pulse_average * video_value_pulse);
 Update_scenario_var_data[33] = (GLfloat)photoWeight * (1.f + pulse_average * photoWeight_pulse);
 Update_scenario_var_data[34] = (GLfloat)photo_hue * (1.f + pulse_average * photo_hue_pulse);
 Update_scenario_var_data[35] = (GLfloat)cameraCumul;
 Update_scenario_var_data[36] = (GLfloat)CAstep;
 Update_scenario_var_data[37] = (GLfloat)CAcolorSpread;
 Update_scenario_var_data[38] = (GLfloat)freeze;
 glUniform1fv( uniform_Update_scenario_var_data, 39, Update_scenario_var_data);

 glUseProgram(shader_programme[pg_shader_Mixing]);
 Mixing_scenario_var_data[0] = (GLfloat)CAMixingWeight * (1.f + pulse_average * CAMixingWeight_pulse) ;
 Mixing_scenario_var_data[1] = (GLfloat)trackMixingWeight_0 * (1.f + pulse_average * trackMixingWeight_0_pulse) ;
 Mixing_scenario_var_data[2] = (GLfloat)trackMixingWeight_1 * (1.f + pulse_average * trackMixingWeight_1_pulse) ;
 Mixing_scenario_var_data[3] = (GLfloat)echo * (1.f + pulse_average * echo_pulse) ;
 Mixing_scenario_var_data[4] = (GLfloat)echoNeg * (1.f + pulse_average * echoNeg_pulse) ;
 glUniform1fv( uniform_Mixing_scenario_var_data, 5, Mixing_scenario_var_data);

 glUseProgram(shader_programme[pg_shader_Master]);
 Master_scenario_var_data[0] = (GLfloat)mute_second_screen;
 Master_scenario_var_data[1] = (GLfloat)invertAllLayers;
 Master_scenario_var_data[2] = (GLfloat)cursorSize;
 Master_scenario_var_data[3] = (GLfloat)master;
 Master_scenario_var_data[4] = (GLfloat)CAMasterWeight * (1.f + pulse_average * CAMasterWeight_pulse);
 Master_scenario_var_data[5] = (GLfloat)trackMasterWeight_0 * (1.f + pulse_average * trackMasterWeight_0_pulse);
 Master_scenario_var_data[6] = (GLfloat)trackMasterWeight_1 * (1.f + pulse_average * trackMasterWeight_1_pulse);
 Master_scenario_var_data[7] = (GLfloat)interfaceOnScreen;
 glUniform1fv( uniform_Master_scenario_var_data, 8, Master_scenario_var_data);
