GLint uniform_Drawing_fs_4fv_particleMode_particle_texture_ID_partAccCenter_0_partAccCenter_1;
GLint uniform_Drawing_fs_4fv_radiusParticle_repopulatingBG_currentDrawingTrack_currentVideoTrack;
GLint uniform_Composition_fs_4fv_echo_echoNeg_trackCompositionWeight_0_trackCompositionWeight_1;
GLint uniform_Final_fs_4fv_blendTransp_invertAllLayers_cursorSize_trackFinalWeight_0;
GLint uniform_Drawing_fs_4fv_track_replay_0_track_replay_1_is_videoOn_is_videoInvert;
GLint uniform_Drawing_fs_4fv_videoThreshold_videoGamma_BGSubtr_images_weights_scale;
GLint uniform_Final_fs_1fv_trackFinalWeight_1;
