echo off

cd C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START .\cavernePlaton.PD.bat

cd C:\sync.com\Sync\LYM-projects\
REM perl C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v4.prl Projects\configuration\LYM_CavernePlaton-head-single.csv Projects\scenarios\LYM_CavernePlaton-scenario-Lieusaint.csv Projects\shaders\LYM_ParticleAnimation_CavernePlaton.frag Projects\shaders\LYM_ParticleAnimation_CavernePlaton_full.frag Projects\shaders\LYM_Update_CavernePlaton.frag Projects\shaders\LYM_Update_CavernePlaton_full.frag Projects\shaders\LYM_Mixing_CavernePlaton.frag Projects\shaders\LYM_Mixing_CavernePlaton_full.frag Projects\shaders\LYM_ParticleSplat_CavernePlaton.frag Projects\shaders\LYM_ParticleSplat_CavernePlaton_full.frag Projects\shaders\LYM_Master_CavernePlaton.frag Projects\shaders\LYM_Master_CavernePlaton_full.frag ..\LYM-sources\Porphyrograph-src\pg_script_header_CavernePlaton.h ..\LYM-sources\Porphyrograph-src\pg_script_body_CavernePlaton.cpp  ..\LYM-sources\Porphyrograph-src\pg_shader_header_CavernePlaton.h ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_CavernePlaton.cpp ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_CavernePlaton.cpp ..\LYM-sources\Porphyrograph-src\pg_update_body_CavernePlaton.cpp
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py --configuration Projects\configuration\LYM_CavernePlaton-head-single.csv --scenario Projects\scenarios\LYM_CavernePlaton-scenario-Lieusaint.csv --particleAnimation_in Projects\shaders\LYM_ParticleAnimation_CavernePlaton.frag --particleAnimation_out Projects\shaders\LYM_ParticleAnimation_CavernePlaton_full.frag --Update_in Projects\shaders\LYM_Update_CavernePlaton.frag --Update_out Projects\shaders\LYM_Update_CavernePlaton_full.frag --Mixing_in Projects\shaders\LYM_Mixing_CavernePlaton.frag --Mixing_out Projects\shaders\LYM_Mixing_CavernePlaton_full.frag --ParticleSplat_in Projects\shaders\LYM_ParticleSplat_CavernePlaton.frag --ParticleSplat_out Projects\shaders\LYM_ParticleSplat_CavernePlaton_full.frag --Master_in Projects\shaders\LYM_Master_CavernePlaton.frag --Master_out Projects\shaders\LYM_Master_CavernePlaton_full.frag --script_header_out ..\LYM-sources\Porphyrograph-src\pg_script_header_CavernePlaton.h --script_body_out ..\LYM-sources\Porphyrograph-src\pg_script_body_CavernePlaton.cpp  --shader_header_out ..\LYM-sources\Porphyrograph-src\pg_shader_header_CavernePlaton.h --shader_body_decl_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_CavernePlaton.cpp --shader_body_bind_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_CavernePlaton.cpp --update_body_out ..\LYM-sources\Porphyrograph-src\pg_update_body_CavernePlaton.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_CavernePlaton\Porphyrograph_core_CavernePlaton.exe ./Projects/configuration/LYM_CavernePlaton-head-single.csv ./Projects/scenarios/LYM_CavernePlaton-scenario-Lieusaint.csv
