echo off

cd C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START .\core.PD.bat

cd C:\sync.com\Sync\LYM-projects\
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py --configuration Projects\configuration\LYM_IME-head-single.csv --scenario Projects\scenarios\LYM_IME-scenario-v1.csv --particleAnimation_in Projects\shaders\LYM_ParticleAnimation_AteliersEnfants.frag --particleAnimation_out Projects\shaders\LYM_ParticleAnimation_AteliersEnfants_full.frag --Update_in Projects\shaders\LYM_Update_AteliersEnfants.frag --Update_out Projects\shaders\LYM_Update_AteliersEnfants_full.frag --Mixing_in Projects\shaders\LYM_Mixing_AteliersEnfants.frag --Mixing_out Projects\shaders\LYM_Mixing_AteliersEnfants_full.frag --ParticleSplat_in Projects\shaders\LYM_ParticleSplat_AteliersEnfants.frag --ParticleSplat_out Projects\shaders\LYM_ParticleSplat_AteliersEnfants_full.frag --Master_in Projects\shaders\LYM_Master_AteliersEnfants.frag --Master_out Projects\shaders\LYM_Master_AteliersEnfants_full.frag --script_header_out ..\LYM-sources\Porphyrograph-src\pg_script_header_AteliersEnfants.h --script_body_out ..\LYM-sources\Porphyrograph-src\pg_script_body_AteliersEnfants.cpp --shader_header_out ..\LYM-sources\Porphyrograph-src\pg_shader_header_AteliersEnfants.h --shader_body_decl_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_AteliersEnfants.cpp --shader_body_bind_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_AteliersEnfants.cpp --update_body_out ..\LYM-sources\Porphyrograph-src\pg_update_body_AteliersEnfants.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_AteliersEnfants\Porphyrograph_core_AteliersEnfants.exe ./Projects/configuration/LYM_IME-head-single.csv ./Projects/scenarios/LYM_IME-scenario-v1.csv
