echo off

cd C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START .\core.PD.bat

cd C:\sync.com\Sync\LYM-projects\
REM perl C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v4.prl Projects\configuration\LYM_Isskjutning-head-single.csv Projects\scenarios\LYM_Isskjutning-scenario-v1.csv Projects\shaders\LYM_ParticleAnimation_Isskjutning.frag Projects\shaders\LYM_ParticleAnimation_Isskjutning_full.frag Projects\shaders\LYM_Update_Isskjutning.frag Projects\shaders\LYM_Update_Isskjutning_full.frag Projects\shaders\LYM_Mixing_Isskjutning.frag Projects\shaders\LYM_Mixing_Isskjutning_full.frag Projects\shaders\LYM_ParticleSplat_Isskjutning.frag Projects\shaders\LYM_ParticleSplat_Isskjutning_full.frag Projects\shaders\LYM_Master_Isskjutning.frag Projects\shaders\LYM_Master_Isskjutning_full.frag ..\LYM-sources\Porphyrograph-src\pg_script_header_Isskjutning.h ..\LYM-sources\Porphyrograph-src\pg_script_body_Isskjutning.cpp  ..\LYM-sources\Porphyrograph-src\pg_shader_header_Isskjutning.h ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_Isskjutning.cpp ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_Isskjutning.cpp ..\LYM-sources\Porphyrograph-src\pg_update_body_Isskjutning.cpp
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py --configuration Projects\configuration\LYM_Isskjutning-head-single.csv --scenario Projects\scenarios\LYM_Isskjutning-scenario-v1.csv --particleAnimation_in Projects\shaders\LYM_ParticleAnimation_Isskjutning.frag --particleAnimation_out Projects\shaders\LYM_ParticleAnimation_Isskjutning_full.frag --Update_in Projects\shaders\LYM_Update_Isskjutning.frag --Update_out Projects\shaders\LYM_Update_Isskjutning_full.frag --Mixing_in Projects\shaders\LYM_Mixing_Isskjutning.frag --Mixing_out Projects\shaders\LYM_Mixing_Isskjutning_full.frag --ParticleSplat_in Projects\shaders\LYM_ParticleSplat_Isskjutning.frag --ParticleSplat_out Projects\shaders\LYM_ParticleSplat_Isskjutning_full.frag --Master_in Projects\shaders\LYM_Master_Isskjutning.frag --Master_out Projects\shaders\LYM_Master_Isskjutning_full.frag --script_header_out ..\LYM-sources\Porphyrograph-src\pg_script_header_Isskjutning.h --script_body_out ..\LYM-sources\Porphyrograph-src\pg_script_body_Isskjutning.cpp  --shader_header_out ..\LYM-sources\Porphyrograph-src\pg_shader_header_Isskjutning.h --shader_body_decl_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_Isskjutning.cpp --shader_body_bind_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_Isskjutning.cpp --update_body_out ..\LYM-sources\Porphyrograph-src\pg_update_body_Isskjutning.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_Isskjutning\Porphyrograph_core_Isskjutning.exe ./Projects/configuration/LYM_Isskjutning-head-single.csv ./Projects/scenarios/LYM_Isskjutning-scenario-v1.csv
