echo off

cd C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START .\cavernePlaton.PD.bat

cd C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py --configuration C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\configuration\LYM_Pierres-head-single_screen.csv --scenario C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\scenarios\LYM_Pierres-scenario-v2-short.csv --particleAnimation_in C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_ParticleAnimation_Pierres.frag --particleAnimation_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_ParticleAnimation_Pierres_full.frag --Update_in C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_Update_Pierres.frag --Update_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_Update_Pierres_full.frag --Mixing_in C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_Mixing_Pierres.frag --Mixing_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_Mixing_Pierres_full.frag --ParticleSplat_in C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_ParticleSplat_Pierres.frag --ParticleSplat_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_ParticleSplat_Pierres_full.frag --Master_in C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_Master_Pierres.frag --Master_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-projects\Projects\shaders\LYM_Master_Pierres_full.frag --script_header_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-sources\Porphyrograph-src\pg_script_header_Pierres.h --script_body_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-sources\Porphyrograph-src\pg_script_body_Pierres.cpp  --shader_header_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-sources\Porphyrograph-src\pg_shader_header_Pierres.h --shader_body_decl_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-sources\Porphyrograph-src\pg_shader_body_decl_Pierres.cpp --shader_body_bind_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-sources\Porphyrograph-src\pg_shader_body_bind_Pierres.cpp --update_body_out C:\sync.com\Sync\LYM-github\Porphyrograph\LYM-sources\Porphyrograph-src\pg_update_body_Pierres.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_PierresArch\Porphyrograph_core_PierresArch.exe C:/sync.com/Sync/LYM-github/Porphyrograph/LYM-projects/Projects/configuration/LYM_Pierres-head-single_screen.csv C:/sync.com/Sync/LYM-github/Porphyrograph/LYM-projects/Projects/scenarios/LYM_Pierres-scenario-v2-short.csv
