echo off

cd C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START .\core.PD.bat

cd C:\sync.com\Sync\LYM-projects\
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py  --configuration Projects\configuration\LYM_SoundInitiative-head-single.csv --scenario Projects\scenarios\LYM_SoundInitiative-Lace-scenario-v2 --particleAnimation_in Projects\shaders\LYM_ParticleAnimation_SoundInitiative.frag --particleAnimation_out Projects\shaders\LYM_ParticleAnimation_SoundInitiative_full.frag --Update_in Projects\shaders\LYM_Update_SoundInitiative.frag --Update_out Projects\shaders\LYM_Update_SoundInitiative_full.frag --Mixing_in Projects\shaders\LYM_Mixing_SoundInitiative.frag --Mixing_out Projects\shaders\LYM_Mixing_SoundInitiative_full.frag --ParticleSplat_in Projects\shaders\LYM_ParticleSplat_SoundInitiative.frag --ParticleSplat_out Projects\shaders\LYM_ParticleSplat_SoundInitiative_full.frag --Master_in Projects\shaders\LYM_Master_SoundInitiative.frag --Master_out Projects\shaders\LYM_Master_SoundInitiative_full.frag --script_header_out ..\LYM-sources\Porphyrograph-src\pg_script_header_SoundInitiative.h --script_body_out ..\LYM-sources\Porphyrograph-src\pg_script_body_SoundInitiative.cpp  --shader_header_out ..\LYM-sources\Porphyrograph-src\pg_shader_header_SoundInitiative.h --shader_body_decl_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_SoundInitiative.cpp --shader_body_bind_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_SoundInitiative.cpp --update_body_out ..\LYM-sources\Porphyrograph-src\pg_update_body_SoundInitiative.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_SoundInitiative\Porphyrograph_core_Core.exe ./Projects/configuration/LYM_SoundInitiative-head-single.csv ./Projects/scenarios/LYM_SoundInitiative-Lace-scenario-v2.csv
