echo off

chdir /d C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START C:\sync.com\Sync\LYM-projects\batFiles\core.PD.bat

chdir /d C:\sync.com\Sync\LYM-projects\
REM perl C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v4.prl Projects\configuration\LYM_Tempete-head-single.csv Projects\scenarios\LYM_Tempete-scenario-v1.csv Projects\shaders\LYM_ParticleAnimation_demo.frag Projects\shaders\LYM_ParticleAnimation_demo_full.frag Projects\shaders\LYM_Update_Tempete.frag Projects\shaders\LYM_Update_Tempete_full.frag Projects\shaders\LYM_Mixing_Tempete.frag Projects\shaders\LYM_Mixing_Tempete_full.frag Projects\shaders\LYM_ParticleSplat_demo.frag Projects\shaders\LYM_ParticleSplat_demo_full.frag Projects\shaders\LYM_Master_Tempete.frag Projects\shaders\LYM_Master_Tempete_full.frag ..\LYM-sources\Porphyrograph-src\pg_script_header_Tempete.h ..\LYM-sources\Porphyrograph-src\pg_script_body_Tempete.cpp  ..\LYM-sources\Porphyrograph-src\pg_shader_header_Tempete.h ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_Tempete.cpp ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_Tempete.cpp ..\LYM-sources\Porphyrograph-src\pg_update_body_Tempete.cpp
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py --configuration Projects\configuration\LYM_Tempete-head-single.csv --scenario Projects\scenarios\LYM_Tempete-scenario-v1.csv --particleAnimation_in Projects\shaders\LYM_ParticleAnimation_demo.frag --particleAnimation_out Projects\shaders\LYM_ParticleAnimation_demo_full.frag --Update_in Projects\shaders\LYM_Update_Tempete.frag --Update_out Projects\shaders\LYM_Update_Tempete_full.frag --Mixing_in Projects\shaders\LYM_Mixing_Tempete.frag --Mixing_out Projects\shaders\LYM_Mixing_Tempete_full.frag --ParticleSplat_in Projects\shaders\LYM_ParticleSplat_Tempete.frag --ParticleSplat_out Projects\shaders\LYM_ParticleSplat_Tempete_full.frag --Master_in Projects\shaders\LYM_Master_Tempete.frag --Master_out Projects\shaders\LYM_Master_Tempete_full.frag --script_header_out ..\LYM-sources\Porphyrograph-src\pg_script_header_Tempete.h --script_body_out ..\LYM-sources\Porphyrograph-src\pg_script_body_Tempete.cpp  --shader_header_out ..\LYM-sources\Porphyrograph-src\pg_shader_header_Tempete.h --shader_body_decl_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_Tempete.cpp --shader_body_bind_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_Tempete.cpp --update_body_out ..\LYM-sources\Porphyrograph-src\pg_update_body_Tempete.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_Tempete\Porphyrograph_core_Tempete.exe ./Projects/configuration/LYM_Tempete-head-single.csv ./Projects/scenarios/LYM_Tempete-scenario-v1.csv
