echo off

cd C:\sync.com\Sync\LYM-projects\batFiles
tasklist /fi "imagename eq pd.exe" |find /i "pd.exe" > nul
if errorlevel 1 START .\core.PD.bat

cd C:\sync.com\Sync\LYM-projects\
REM perl C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v4.prl Projects\configuration\LYM_voluspa-head-single.csv Projects\scenarios\LYM_voluspa-scenario-v1.csv Projects\shaders\LYM_ParticleAnimation_voluspa.frag Projects\shaders\LYM_ParticleAnimation_voluspa_full.frag Projects\shaders\LYM_Update_voluspa.frag Projects\shaders\LYM_Update_voluspa_full.frag Projects\shaders\LYM_Mixing_voluspa.frag Projects\shaders\LYM_Mixing_voluspa_full.frag Projects\shaders\LYM_ParticleSplat_voluspa.frag Projects\shaders\LYM_ParticleSplat_voluspa_full.frag Projects\shaders\LYM_Master_voluspa.frag Projects\shaders\LYM_Master_voluspa_full.frag ..\LYM-sources\Porphyrograph-src\pg_script_header_voluspa.h ..\LYM-sources\Porphyrograph-src\pg_script_body_voluspa.cpp  ..\LYM-sources\Porphyrograph-src\pg_shader_header_voluspa.h ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_voluspa.cpp ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_voluspa.cpp ..\LYM-sources\Porphyrograph-src\pg_update_body_voluspa.cpp
python C:\sync.com\Sync\LYM-projects\Projects\cmd\PG_confGenerator_Projects-v1.py --configuration Projects\configuration\LYM_voluspa-head-single.csv --scenario Projects\scenarios\LYM_voluspa-scenario-v1.csv --particleAnimation_in Projects\shaders\LYM_ParticleAnimation_voluspa.frag --particleAnimation_out Projects\shaders\LYM_ParticleAnimation_voluspa_full.frag --Update_in Projects\shaders\LYM_Update_voluspa.frag --Update_out Projects\shaders\LYM_Update_voluspa_full.frag --Mixing_in Projects\shaders\LYM_Mixing_voluspa.frag --Mixing_out Projects\shaders\LYM_Mixing_voluspa_full.frag --ParticleSplat_in Projects\shaders\LYM_ParticleSplat_voluspa.frag --ParticleSplat_out Projects\shaders\LYM_ParticleSplat_voluspa_full.frag --Master_in Projects\shaders\LYM_Master_voluspa.frag --Master_out Projects\shaders\LYM_Master_voluspa_full.frag --script_header_out ..\LYM-sources\Porphyrograph-src\pg_script_header_voluspa.h --script_body_out ..\LYM-sources\Porphyrograph-src\pg_script_body_voluspa.cpp  --shader_header_out ..\LYM-sources\Porphyrograph-src\pg_shader_header_voluspa.h --shader_body_decl_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_decl_voluspa.cpp --shader_body_bind_out ..\LYM-sources\Porphyrograph-src\pg_shader_body_bind_voluspa.cpp --update_body_out ..\LYM-sources\Porphyrograph-src\pg_update_body_voluspa.cpp
C:\sync.com\Sync\LYM-sources\Porphyrograph-VC17\Release\core_voluspa\Porphyrograph_core_voluspa.exe ./Projects/configuration/LYM_voluspa-head-single.csv ./Projects/scenarios/LYM_voluspa-scenario-v1.csv
