cat dm-all_include.h | ./transcode.prl > vcl-all_include.h
cat dm-composition.cpp | ./transcode.prl > vcl-composition.cpp
cat dm-composition.h | ./transcode.prl > vcl-composition.h
cat dm-conf.cpp | ./transcode.prl > vcl-conf.cpp
cat dm-conf.h | ./transcode.prl > vcl-conf.h
cat dm-draw.cpp | ./transcode.prl > vcl-draw.cpp
cat dm-draw.h | ./transcode.prl > vcl-draw.h
cat dm-geom-objects.cpp | ./transcode.prl > vcl-geom-objects.cpp
cat dm-geom-objects.h | ./transcode.prl > vcl-geom-objects.h
cat dm-interpolator.cpp | ./transcode.prl > vcl-interpolator.cpp
cat dm-interpolator.h | ./transcode.prl > vcl-interpolator.h
cat dm-IOfile.cpp | ./transcode.prl > vcl-IOfile.cpp
cat dm-IOfile.h | ./transcode.prl > vcl-IOfile.h
cat dm-lib.cpp | ./transcode.prl > vcl-lib.cpp
cat dm-lib.h | ./transcode.prl > vcl-lib.h
cat dm-main.cpp | ./transcode.prl > vcl-main.cpp
cat dm-main.h | ./transcode.prl > vcl-main.h
cat dm-material.cpp | ./transcode.prl > vcl-material.cpp
cat dm-material.h | ./transcode.prl > vcl-material.h
cat dm-non-geom-objects.cpp | ./transcode.prl > vcl-non-geom-objects.cpp
cat dm-non-geom-objects.h | ./transcode.prl > vcl-non-geom-objects.h
cat dm-scene.cpp | ./transcode.prl > vcl-scene.cpp
cat dm-scene.h | ./transcode.prl > vcl-scene.h
cat dm-script.cpp | ./transcode.prl > vcl-script.cpp
cat dm-script.h | ./transcode.prl > vcl-script.h
cat dm-shader.cpp | ./transcode.prl > vcl-shader.cpp
cat dm-shader.h | ./transcode.prl > vcl-shader.h
cat dm-strings.cpp | ./transcode.prl > vcl-strings.cpp
cat dm-strings.h | ./transcode.prl > vcl-strings.h
cat dm-texture.cpp | ./transcode.prl > vcl-texture.cpp
cat dm-texture.h | ./transcode.prl > vcl-texture.h
cat dm-udp.cpp | ./transcode.prl > vcl-udp.cpp
cat dm-udp.h | ./transcode.prl > vcl-udp.h
cat dm-variables.cpp | ./transcode.prl > vcl-variables.cpp
cat dm-variables.h | ./transcode.prl > vcl-variables.h
cat dm-video.cpp | ./transcode.prl > vcl-video.cpp
cat dm-video.h | ./transcode.prl > vcl-video.h
