extern GLint uniform_ParticleAnimation_scenario_var_data[1];
extern GLint uniform_Mixing_scenario_var_data[1];
extern GLint uniform_Update_scenario_var_data[1];
extern GLint uniform_ParticleRender_scenario_var_data[1];
extern GLint uniform_Master_scenario_var_data[1];
extern float *ParticleAnimation_scenario_var_data;
extern float *Update_scenario_var_data;
extern float *Mixing_scenario_var_data;
extern float *Master_scenario_var_data;
